@echo off

SET JSDir=C:\AppServ\www\a3k_t\js\full\

CALL JsMinfy.bat %JSDir% a3k.css
CALL JsMinfy.bat %JSDir% a3konhinet.css
CALL JsMinfy.bat %JSDir% a3konlocal.css
CALL JsMinfy.bat %JSDir% admin.css
CALL JsMinfy.bat %JSDir% city.css
CALL JsMinfy.bat %JSDir% city140.css
CALL JsMinfy.bat %JSDir% city141.css

CALL JsMinfy.bat %JSDir% a3k.js
CALL JsMinfy.bat %JSDir% bag.js
CALL JsMinfy.bat %JSDir% bag2.js
CALL JsMinfy.bat %JSDir% bank.js
CALL JsMinfy.bat %JSDir% bro_info.js
CALL JsMinfy.bat %JSDir% capt.js
CALL JsMinfy.bat %JSDir% chat.js
CALL JsMinfy.bat %JSDir% city.js
CALL JsMinfy.bat %JSDir% create.js
CALL JsMinfy.bat %JSDir% create_2.js 
CALL JsMinfy.bat %JSDir% fellow.js
CALL JsMinfy.bat %JSDir% fellow_trade.js
CALL JsMinfy.bat %JSDir% fellow_info.js 
CALL JsMinfy.bat %JSDir% fight.js 
CALL JsMinfy.bat %JSDir% group.js
CALL JsMinfy.bat %JSDir% index.js 
CALL JsMinfy.bat %JSDir% json2.js 
CALL JsMinfy.bat %JSDir% map.js 
CALL JsMinfy.bat %JSDir% mail.js 
CALL JsMinfy.bat %JSDir% mix.js
CALL JsMinfy.bat %JSDir% message.js 
CALL JsMinfy.bat %JSDir% mmsg.js 
CALL JsMinfy.bat %JSDir% fmsg.js 
CALL JsMinfy.bat %JSDir% new.js
CALL JsMinfy.bat %JSDir% newfight.js
CALL JsMinfy.bat %JSDir% newfellow_info.js
CALL JsMinfy.bat %JSDir% newplayer_info.js
CALL JsMinfy.bat %JSDir% newplayer_info2.js
CALL JsMinfy.bat %JSDir% newskill_info.js 
CALL JsMinfy.bat %JSDir% npclist.js 
CALL JsMinfy.bat %JSDir% player_info.js 
CALL JsMinfy.bat %JSDir% popup.js 
CALL JsMinfy.bat %JSDir% quest.js 
CALL JsMinfy.bat %JSDir% role_info.js 
CALL JsMinfy.bat %JSDir% shop.js 
CALL JsMinfy.bat %JSDir% sell.js 
CALL JsMinfy.bat %JSDir% skill_info.js 
CALL JsMinfy.bat %JSDir% store.js 
CALL JsMinfy.bat %JSDir% x.js 
CALL JsMinfy.bat %JSDir% new.js 
CALL JsMinfy.bat %JSDir% look.js 

CALL JsMinfy.bat %JSDir% bag.html
CALL JsMinfy.bat %JSDir% bag_1.html
CALL JsMinfy.bat %JSDir% bag_2.html
CALL JsMinfy.bat %JSDir% bag_3.html
CALL JsMinfy.bat %JSDir% bag_4.html
CALL JsMinfy.bat %JSDir% bank.html
CALL JsMinfy.bat %JSDir% brother_info.html
CALL JsMinfy.bat %JSDir% capt.html
CALL JsMinfy.bat %JSDir% chat.html
CALL JsMinfy.bat %JSDir% city.html
CALL JsMinfy.bat %JSDir% city140.html	
CALL JsMinfy.bat %JSDir% city142.html
CALL JsMinfy.bat %JSDir% city143.html
CALL JsMinfy.bat %JSDir% city144.html
CALL JsMinfy.bat %JSDir% city145.html
CALL JsMinfy.bat %JSDir% city146.html
CALL JsMinfy.bat %JSDir% city147.html
CALL JsMinfy.bat %JSDir% city148.html
CALL JsMinfy.bat %JSDir% city149.html
CALL JsMinfy.bat %JSDir% city1410.html
CALL JsMinfy.bat %JSDir% city1412.html
CALL JsMinfy.bat %JSDir% city1413.html
CALL JsMinfy.bat %JSDir% city1414.html
CALL JsMinfy.bat %JSDir% city1415.html
CALL JsMinfy.bat %JSDir% create.html
CALL JsMinfy.bat %JSDir% create_2.html
CALL JsMinfy.bat %JSDir% create_3.html
CALL JsMinfy.bat %JSDir% fellow.html
CALL JsMinfy.bat %JSDir% fellow_trade.html
CALL JsMinfy.bat %JSDir% fellow_info.html 
CALL JsMinfy.bat %JSDir% fight.html 
CALL JsMinfy.bat %JSDir% group.html
CALL JsMinfy.bat %JSDir% group2.html
CALL JsMinfy.bat %JSDir% group3.html
CALL JsMinfy.bat %JSDir% group4.html
CALL JsMinfy.bat %JSDir% group5.html
CALL JsMinfy.bat %JSDir% group6.html
CALL JsMinfy.bat %JSDir% group7.html
CALL JsMinfy.bat %JSDir% group8.html
CALL JsMinfy.bat %JSDir% group9.html
CALL JsMinfy.bat %JSDir% guide_map.html
CALL JsMinfy.bat %JSDir% index.html 
CALL JsMinfy.bat %JSDir% look.html 
CALL JsMinfy.bat %JSDir% map.html 
CALL JsMinfy.bat %JSDir% mail.html 
CALL JsMinfy.bat %JSDir% mail_2.html 
CALL JsMinfy.bat %JSDir% map_2.html 
CALL JsMinfy.bat %JSDir% mix.html
CALL JsMinfy.bat %JSDir% mix_2.html
CALL JsMinfy.bat %JSDir% message.html 
CALL JsMinfy.bat %JSDir% mission.html
CALL JsMinfy.bat %JSDir% mission_1.html
CALL JsMinfy.bat %JSDir% mission_2.html
CALL JsMinfy.bat %JSDir% mission_3.html
CALL JsMinfy.bat %JSDir% mission_4.html
CALL JsMinfy.bat %JSDir% newb.html
CALL JsMinfy.bat %JSDir% msgpopup.html
CALL JsMinfy.bat %JSDir% monster.html
CALL JsMinfy.bat %JSDir% newbag.html
CALL JsMinfy.bat %JSDir% newbag2.html
CALL JsMinfy.bat %JSDir% newfellow_info.html
CALL JsMinfy.bat %JSDir% newfight.html
CALL JsMinfy.bat %JSDir% newmessage1.html
CALL JsMinfy.bat %JSDir% newskill_info.html 
CALL JsMinfy.bat %JSDir% newplayer_info.html 
CALL JsMinfy.bat %JSDir% newplayer_info2.html 
CALL JsMinfy.bat %JSDir% npclist.html 
CALL JsMinfy.bat %JSDir% player_info.html 
CALL JsMinfy.bat %JSDir% role_info.html 
CALL JsMinfy.bat %JSDir% sell.html 
CALL JsMinfy.bat %JSDir% shop_buy1.html 
CALL JsMinfy.bat %JSDir% shop_buy2.html 
CALL JsMinfy.bat %JSDir% skill_info.html 
CALL JsMinfy.bat %JSDir% skill.html 
CALL JsMinfy.bat %JSDir% store.html 
